
name: Maven Package By Ronen Bar

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
       
       run: mvn -B package --file pom.xml
     - name:  step3  ls the vm
       run: ls -a
     - name: chenge dirctory 
       run: |
          cd target
          ls -a

   
